config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update, :destroy]

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  deadline   :date             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :content, uniqueness: true
  validates :deadline, presence: true

  has_one_attached :eyecatch

  belongs_to :board

  belongs_to :user

  has_many :comments, dependent: :destroy

  def day
    return '不明' unless deadline.present?
    days = deadline.yday - Time.zone.now.yday
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def show
    @comments = @task.comments
  end

  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params.merge!(user_id: current_user.id))
    if @task.save
      redirect_to board_path(board), notice: 'タスクを追加'
    else
      flash.now[:error] = 'タスクを追加できませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to board_task_path(board_id: @task.board_id, id: @task.id), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:id])
    task.destroy!
    redirect_to board_path(board), notice: '削除に成功しました'
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :deadline, :eyecatch)
  end

  def set_task
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
  end
end

app/views/tasks/edit.html.haml
.container
  %h2 Edit Card
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: board_task_path(@task.board), local: true) do |f|
    %div
      = f.label :eyecatch, 'Eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :deadline, 'Deadline'
    %div
      = f.date_field :deadline, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/new.html.haml
.container
  %h2 New Card
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: board_tasks_path(@task.board), local: true) do |f|
    %div
      = f.label :eyecatch, 'Eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :deadline, 'Deadline'
    %div
      = f.date_field :deadline, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.container
  .task_header
    %h2= @task.title
    .task_header_detail
      %div
        - if user_signed_in? && current_user.has_task_written?(@task)
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to 'Edit', edit_board_task_path(board_id: @task.board_id, id: @task.id)
              = link_to 'Delete', board_task_path(board_id: @task.board_id, id: @task.id), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
.container
  - if @task.eyecatch.attached?
    .task_image
      = image_tag @task.eyecatch
.task
  .task_content
    %p= @task.content
.container
  %h2 Comment
- @comments.each do |comment|
  .comment
    .comment_detail
      = image_tag comment.user.avatar_image
    .comment_content
      %p= comment.content
.container
  = link_to new_board_task_comment_path(board_id: @task.board_id, task_id: @task.id) do
    .float_btn_min
      %i.fa.fa-plus  Add new comment