config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update, :destroy]

end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord

  validates :title, presence: true

  validates :content, presence: true
  validates :content, uniqueness: true

  has_many :tasks, dependent: :destroy
  belongs_to :user

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: '保存できたよ'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content, :eyecatch)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/views/boards/_board.html.haml
= link_to board_path(board) do
  .card
    %h1.card_title
      = board.title
    .card_content
      = board.content
    .card_detail
      = image_tag board.user.avatar_image
      %div
        - if board.user.present?
          %p= board.user.display_name
          %p= board.display_created_at
      - if user_signed_in? && current_user.has_written?(board)
        .card_detail_actions
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to 'Edit', edit_board_path(board)
              = link_to 'Delete', board_path(board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }

app/views/boards/_form.html.haml
.container
  %h2 New Board
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: board, local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/_tabs.html.haml
%h2 All Boards

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
  = render 'tabs'
  - @boards.each do |board|
    = render 'board', board: board
  = link_to new_board_path do
    .float_btn
      %i.fa.fa-plus  Add new borad

app/views/boards/new.html.haml
= render 'form', board: @board

app/views/boards/show.html.haml
.container
  %h2= @board.title
- @tasks.each do |task|
  = link_to board_task_path(board_id: @board.id, id: task.id) do
    .task
      - if task.eyecatch.attached?
        .task_image
          = image_tag task.eyecatch
      %h1.task_title= task.title
      .task_content
        %p= task.content
      .task_detail
        = image_tag @board.user.avatar_image
      .task_heart
        %span
          #{task.day}
        = image_tag 'message-square-outline.svg'
.container
  = link_to new_board_task_path(@board) do
    .float_btn
      %i.fa.fa-plus  Add new card